### PR TITLE
Setters and getters for actor properties

### PR DESCRIPTION
**Pull request by marioyc**

### CODE REVIEW

**Comment by adamlerer** [comment]
Excellent! Thanks @marioyc . In the future, I would like to see if we can add FVector/FRotator and maybe a couple other things to the accepted arguments in ScriptPluginGenerator, which should allow all these bindings to be autogenerated.

**Comment by adamlerer** [comment]
@marioyc I already merged this but when you get a chance can you add some info about these functions to the README tutorial and the uetorch_example.lua script?

**Comment by marioyc** [comment]
Yes, I'll be adding that in the coming days, and also the project will be available as an example at https://github.com/bootphon/NaivePhysics

**Comment by adamlerer** [comment]
Great!

**Pull request merged**
