### PR TITLE
Added Windows support

### PR DESCRIPTION
**Pull request by yhase7**
Added following features for supporting Windows
- Added ~_API descriptions
- Modified uetorch.lua file for loading functions from the DLL
- Added .bat files instead of .sh files
- Added the .patch file for Windows

### CODE REVIEW

**Comment by adamlerer** [comment]
This is fantastic, thanks @yhase7 ! It doesn't look like you modify anything that would affect the Linux version, but did you get to test it?

Also, could you add info to the README explaining how to install on Windows?

Other than that, it looks ready to merge. Thanks!

**Comment by yhase7** [comment]
Thank you for your reply!

I added info about installing and running on Windows. Please review it.

I have modified source codes carefully so as not to affect the Linux version, but I haven't still check it because I don't have a Linux machine which is able to run UE4. If you could wait a moment, I'll test it after the Linux machine is ready.

Thanks.

**Comment by yhase7** [comment]
I tested installing and running uetorch_example.lua on Linux, and it succeeded.

**Comment by adamlerer** [comment]
Cool! For the README, would it be possible to just put the modified windows commands inline into the other section where appropriate, instead of making new sections? E.g.

2. Download / install torch ...
Linux
```
TORCH_LUA_VERSION=LUA52 ./install.sh
```
Windows
```
set TORCH_LUA_VERSION=LUA52
./install.bat
```

**Comment by yhase7** [comment]
Thanks! I moved info about Windows. Please review it.

**Comment by adamlerer** [comment]
Awesome. Thanks @yhase7 !

**Pull request merged**
